# Autostart
exec-once = swww-daemon
exec-once = sh -c 'sleep 0.5; swww img ~/.dotfiles/assets/wallpaper/5.jpg'
exec-once = playerctld
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/volume_listener.sh
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
exec-once = quickshell -p ~/.config/hypr/scripts/quickshell/Shell.qml
exec-once = quickshell -c qs-hyprview
exec-once = python3 ~/.config/hypr/scripts/quickshell/focustime/focus_daemon.py &
