# Layer rules
layerrule = noanim, ^(volume_osd)$
layerrule = noanim, ^(brightness_osd)$
layerrule = noanim, hyprpicker
layerrule = noanim, qsdock
layerrule = blur, ext-session-lock
layerrule = ignorealpha 0.2, ext-session-lock
layerrule = dimaround, quickshell:expose
layerrule = blur, quickshell:expose

# Window rules
windowrulev2 = immediate, class:^(cs2)$
windowrulev2 = keepaspectratio, class:^(cs2)$
windowrulev2 = float, title:^(app-launcher)$
windowrulev2 = center, title:^(app-launcher)$
windowrulev2 = size 1200 600, title:^(app-launcher)$
windowrulev2 = animation slide, title:^(app-launcher)$
