# Wallpaper-driven theming.
#
# Noctalia extracts a Material palette from the active wallpaper and renders it
# through its template engine every time the wallpaper or colour scheme changes.
# This module owns the parts of that pipeline that are specific to this repo:
#
#   * the user templates (things Noctalia has no built-in or community template
#     for), rendered into $XDG_CONFIG_HOME/noctalia/templates,
#   * the seed files, so every consumer has a valid colour file on a fresh
#     machine, before Noctalia has ever applied a palette,
#   * the oh-my-posh generator, which cannot be a plain template because
#     oh-my-posh prompt configs use `{{ }}` for their own segment templates and
#     would collide with Noctalia's expression syntax.
#
# The template list itself is consumed by modules/gui/noctalia.nix, which is
# what writes it into Noctalia's config.
{
  lib,
  pkgs,
  config,
  inputs,
  hostVariables,
  ...
}: let
  cfg = config.modules.gui.theming;

  homeDir = "/home/${hostVariables.username}";
  configDir = "${homeDir}/.config";
  cacheDir = "${homeDir}/.cache/noctalia";
  templateDir = "${configDir}/noctalia/templates";

  palette = import ./palette.nix;

  # LibreWolf keeps one chrome/ directory per profile, and userChrome.css is a
  # read-only Home Manager symlink, so the generated colours go in a sibling
  # file that userChrome.css imports. Keep in sync with the profile set in
  # modules/software/librewolf.nix.
  librewolfProfiles = ["default" "anon" "persona"];

  # A flat colour map, rendered for the benefit of hook scripts that need the
  # palette as data rather than as a finished config file.
  colorsTemplate = ''
    {
      "primary": "{{colors.primary.default.hex}}",
      "on_primary": "{{colors.on_primary.default.hex}}",
      "secondary": "{{colors.secondary.default.hex}}",
      "on_secondary": "{{colors.on_secondary.default.hex}}",
      "tertiary": "{{colors.tertiary.default.hex}}",
      "on_tertiary": "{{colors.on_tertiary.default.hex}}",
      "error": "{{colors.error.default.hex}}",
      "on_error": "{{colors.on_error.default.hex}}",
      "surface": "{{colors.surface.default.hex}}",
      "on_surface": "{{colors.on_surface.default.hex}}",
      "surface_variant": "{{colors.surface_variant.default.hex}}",
      "on_surface_variant": "{{colors.on_surface_variant.default.hex}}",
      "surface_container": "{{colors.surface_container.default.hex}}",
      "surface_container_high": "{{colors.surface_container_high.default.hex}}",
      "outline": "{{colors.outline.default.hex}}"
    }
  '';

  # Mirrors the --lw-* custom properties that modules/software/librewolf.nix
  # used to hardcode; userChrome.css now only consumes them.
  librewolfTemplate = ''
    /* Generated by Noctalia from the active wallpaper. */
    :root {
      --lw-bg: {{colors.surface.default.hex}};
      --lw-bg-elevated: {{colors.surface_container.default.hex}};
      --lw-bg-hover: {{colors.surface_container_high.default.hex}};
      --lw-bg-active: {{colors.surface_container_highest.default.hex}};
      --lw-border: {{colors.outline.default.hex}};
      --lw-text: {{colors.on_surface.default.hex}};
      --lw-muted: {{colors.on_surface_variant.default.hex}};
      --lw-accent: {{colors.primary.default.hex}};
      --lw-accent-strong: {{colors.secondary.default.hex}};
    }
  '';

  ompSource = ../console/oh-my-posh/theme/atomic.omp.json;

  # oh-my-posh's own `{{ .Path }}`-style segment templates use the same
  # delimiters as Noctalia's template engine, so the prompt is recoloured with
  # jq against the rendered colour map instead of being run through Noctalia.
  # Only the structural segments are repainted; the language segments keep
  # their brand colours (Python blue, Node green, ...).
  ompGenerator = pkgs.writeShellApplication {
    name = "noctalia-oh-my-posh";
    runtimeInputs = [pkgs.jq];
    text = ''
      colors="''${1:-${cacheDir}/colors.json}"
      out="${configDir}/oh-my-posh/noctalia.json"

      [ -r "$colors" ] || exit 0
      mkdir -p "$(dirname "$out")"

      tmp="$(mktemp "$out.XXXXXX")"
      trap 'rm -f "$tmp"' EXIT

      jq --argjson c "$(cat "$colors")" '
        def paint($bg; $fg): .background = $bg | .foreground = $fg;
        .blocks |= map(
          .segments |= map(
            if   .type == "shell"         then paint($c.primary; $c.on_primary)
            elif .type == "root"          then paint($c.error; $c.on_error)
            elif .type == "path"          then paint($c.secondary; $c.on_secondary)
            elif .type == "git"           then paint($c.tertiary; $c.on_tertiary)
                                               | del(.background_templates)
            elif .type == "executiontime" then paint($c.surface_container_high; $c.on_surface)
            elif .type == "time"          then paint($c.surface_container_high; $c.on_surface)
            elif .type == "status"        then paint($c.surface_container_high; $c.on_surface)
            else . end
          )
        )
      ' ${ompSource} > "$tmp"

      trap - EXIT
      mv "$tmp" "$out"
    '';
  };

  # ── Seeds ───────────────────────────────────────────────────────────────────
  # Every consumer below reads a mutable file that Noctalia owns at runtime.
  # Until the first palette is applied those files do not exist, which would
  # leave alacritty importing a missing file and oh-my-posh with no config at
  # all, so each one is seeded from the static Urban palette.

  seedAlacritty = pkgs.writeText "noctalia-seed-alacritty.toml" ''
    [colors.primary]
    background = '${palette.background}'
    foreground = '${palette.foreground}'

    [colors.cursor]
    text = '${palette.background}'
    cursor = '${palette.foreground}'

    [colors.selection]
    text = '${palette.background}'
    background = '${palette.foreground}'

    [colors.normal]
    black   = '${palette.normal.black}'
    red     = '${palette.normal.red}'
    green   = '${palette.normal.green}'
    yellow  = '${palette.normal.yellow}'
    blue    = '${palette.normal.blue}'
    magenta = '${palette.normal.magenta}'
    cyan    = '${palette.normal.cyan}'
    white   = '${palette.normal.white}'

    [colors.bright]
    black   = '${palette.bright.black}'
    red     = '${palette.bright.red}'
    green   = '${palette.bright.green}'
    yellow  = '${palette.bright.yellow}'
    blue    = '${palette.bright.blue}'
    magenta = '${palette.bright.magenta}'
    cyan    = '${palette.bright.cyan}'
    white   = '${palette.bright.white}'
  '';

  seedGtk = pkgs.writeText "noctalia-seed-gtk.css" ''
    @define-color accent_color ${palette.normal.blue};
    @define-color accent_bg_color ${palette.normal.blue};
    @define-color accent_fg_color ${palette.normal.black};
    @define-color destructive_bg_color ${palette.normal.red};
    @define-color destructive_fg_color ${palette.foreground};
    @define-color error_bg_color ${palette.normal.red};
    @define-color error_fg_color ${palette.foreground};
    @define-color window_bg_color ${palette.normal.black};
    @define-color window_fg_color ${palette.foreground};
    @define-color view_bg_color ${palette.normal.black};
    @define-color view_fg_color ${palette.foreground};
    @define-color headerbar_bg_color ${palette.background};
    @define-color headerbar_fg_color ${palette.foreground};
    @define-color sidebar_bg_color ${palette.background};
    @define-color sidebar_fg_color ${palette.foreground};
    @define-color card_bg_color ${palette.background};
    @define-color card_fg_color ${palette.foreground};
    @define-color popover_bg_color ${palette.background};
    @define-color popover_fg_color ${palette.foreground};
    @define-color dialog_bg_color ${palette.background};
    @define-color dialog_fg_color ${palette.foreground};
  '';

  seedColors = pkgs.writeText "noctalia-seed-colors.json" (builtins.toJSON {
    primary = palette.normal.blue;
    on_primary = palette.normal.black;
    secondary = palette.normal.cyan;
    on_secondary = palette.normal.black;
    tertiary = palette.normal.magenta;
    on_tertiary = palette.normal.black;
    error = palette.normal.red;
    on_error = palette.foreground;
    surface = palette.normal.black;
    on_surface = palette.foreground;
    surface_variant = palette.background;
    on_surface_variant = palette.roles.mOnSurfaceVariant;
    surface_container = palette.client.bg3;
    surface_container_high = palette.bright.black;
    outline = palette.bright.black;
  });

  seedLibrewolf = pkgs.writeText "noctalia-seed-librewolf.css" ''
    :root {
      --lw-bg: ${palette.normal.black};
      --lw-bg-elevated: ${palette.client.bg3};
      --lw-bg-hover: ${palette.bright.black};
      --lw-bg-active: ${palette.client.bg3};
      --lw-border: ${palette.bright.black};
      --lw-text: ${palette.foreground};
      --lw-muted: ${palette.roles.mOnSurfaceVariant};
      --lw-accent: ${palette.normal.blue};
      --lw-accent-strong: ${palette.normal.cyan};
    }
  '';

  # VSCode loads extensions from ~/.vscode/extensions in addition to the ones
  # baked into the package. The community template rewrites the theme JSON
  # inside that directory, which only works on a writable copy.
  vscodeThemeExt = "noctalia.noctaliatheme-0.0.5";
  vscodeThemePkg =
    (import inputs.nixpkgs {
      inherit (pkgs.stdenv.hostPlatform) system;
      config.allowUnfree = true;
      overlays = [inputs.nix-vscode-extensions.overlays.default];
    })
    .vscode-marketplace.noctalia.noctaliatheme;

  seedLines =
    [
      "seed ${seedAlacritty} ${configDir}/alacritty/themes/noctalia.toml"
      "seed ${seedGtk} ${configDir}/gtk-3.0/noctalia.css"
      "seed ${seedGtk} ${configDir}/gtk-4.0/noctalia.css"
      "seed ${seedColors} ${cacheDir}/colors.json"
    ]
    ++ lib.optionals config.modules.software.librewolf.enable (map
      (p: "seed ${seedLibrewolf} ${homeDir}/.librewolf/${p}/chrome/noctalia.css")
      librewolfProfiles);
in {
  options.modules.gui.theming = {
    enable =
      lib.mkEnableOption "wallpaper-driven theming of every themed application"
      // {default = config.modules.gui.noctalia.enable;};

    userTemplates = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      readOnly = true;
      description = ''
        Noctalia `theme.templates.user.*` entries contributed by this module.
        Consumed by modules/gui/noctalia.nix.
      '';
      default = {
        # Rendered first (index -1) so the oh-my-posh hook and anything else
        # reading colors.json sees the new palette rather than the previous one.
        colors = {
          input_path = "${templateDir}/colors.json";
          output_path = "${cacheDir}/colors.json";
          post_hook = "${lib.getExe ompGenerator} ${cacheDir}/colors.json";
          hook_async = false;
          index = -1;
        };

        librewolf = {
          input_path = "${templateDir}/librewolf.css";
          output_path =
            map (p: "${homeDir}/.librewolf/${p}/chrome/noctalia.css")
            librewolfProfiles;
        };
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # Takes home-manager's lib, which carries the hm.dag helpers.
    home-manager.users.${hostVariables.username} = {lib, ...}: {
      home.packages = [ompGenerator];

      xdg.configFile = {
        "noctalia/templates/colors.json".text = colorsTemplate;
        "noctalia/templates/librewolf.css".text = librewolfTemplate;
      };

      # `seed` never overwrites: once Noctalia has rendered a palette these
      # files are its own, and a rebuild must not stomp the live colours.
      home.activation.noctaliaThemeSeeds = lib.hm.dag.entryAfter ["writeBoundary"] ''
        seed() {
          [ -e "$2" ] && return 0
          run mkdir -p "$(dirname "$2")"
          run install -m644 "$1" "$2"
        }

        ${lib.concatStringsSep "\n" seedLines}

        # oh-my-posh has no usable fallback: without a config the prompt
        # fails outright, so seed it from the unmodified upstream theme.
        seed ${ompSource} ${configDir}/oh-my-posh/noctalia.json

        ${lib.optionalString config.modules.software.vscode.enable ''
          # A writable copy of the theme extension, so the template has
          # somewhere to write. Copied rather than linked, and left alone once
          # it exists.
          if [ ! -e "${homeDir}/.vscode/extensions/${vscodeThemeExt}" ]; then
            run mkdir -p "${homeDir}/.vscode/extensions"
            run cp -r \
              "${vscodeThemePkg}/share/vscode/extensions/noctalia.noctaliatheme" \
              "${homeDir}/.vscode/extensions/${vscodeThemeExt}"
            run chmod -R u+w "${homeDir}/.vscode/extensions/${vscodeThemeExt}"
          fi
        ''}
      '';
    };
  };
}
