{
  imports = [
    ./collabora.nix
    ./displaylink.nix
    ./docker.nix
    ./couchdb.nix
    ./fail2ban.nix
    ./flatpak.nix
    ./git.nix
    ./immich.nix
    ./noisetorch.nix
    ./obsidian.nix
    ./vscode.nix
    ./tailscale.nix
    ./vencord.nix
    ./opencloud.nix
    ./paperless-ngx.nix
    ./spicetify.nix
    ./sunshine.nix
  ];
}
