{
  imports = [
    ./collabora.nix
    ./chessstack.nix
    ./displaylink.nix
    ./docker.nix
    ./couchdb.nix
    ./fail2ban.nix
    ./flatpak.nix
    ./git.nix
    ./immich.nix
    ./lm-studio.nix
    ./librewolf.nix
    ./noisetorch.nix
    ./obsidian.nix
    ./osu.nix
    ./vscode.nix
    ./tailscale.nix
    ./vencord.nix
    ./opencloud.nix
    ./paperless-ngx.nix
    ./spicetify.nix
    ./sunshine.nix
    ./mealie.nix
    ./freshrss.nix
    ./nixvim.nix
    ./zed.nix
  ];
}
